version: '3.8'
services:
  mongo-primary:
    image: mongo:latest
    container_name: mongo-primary
    ports:
      - 27017:27017
    command: mongod --replSet rsTournament --bind_ip_all
    networks:
      - mongo-cluster
  mongo-secondary1:
    image: mongo:latest
    container_name: mongo-secondary1
    command: mongod --replSet rsTournament --bind_ip_all
    networks:
      - mongo-cluster
  mongo-secondary2:
    image: mongo:latest
    container_name: mongo-secondary2
    command: mongod --replSet rsTournament --bind_ip_all
    networks:
      - mongo-cluster
networks:
  mongo-cluster:
    driver: bridge
